import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdtemp } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test, { after } from "node:test";
import { fileURLToPath } from "node:url";

// `with-private.sh` swaps the real private crate over the public stub for the
// duration of one command and puts the stub back from a trap. The trap cannot
// cover SIGKILL — `check-no-private.sh` says so in its own header — so a killed
// run leaves the private sources in the tree. That much is known and the commit
// guard catches it.
//
// What these tests pin is the SECOND failure, the one that turns a single kill
// into a standing condition: the script snapshots whatever is at
// `crates/sealwire-private` as "the stub" WITHOUT checking that it is one. On a
// tree a previous run left swapped, the snapshot is the private sources, and the
// trap then faithfully restores them. The restore works perfectly; it is
// restoring the wrong thing. Every later run re-poisons a tree that was cleaned
// by hand in between, which is what makes it look like an intermittent trap.
//
// The tell is the stub's own STUB marker file — the same one `dev-full.mjs` and
// `check-no-private.sh` already key off. with-private.sh is the only one of the
// three that does not look at it.

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const realScript = path.join(repoRoot, "scripts/with-private.sh");

const tempDirs = [];
after(() => {
  for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true });
});

const CLEAN_LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "sealwire-private"
version = "0.1.0"

[[package]]
name = "relay-api"
version = "0.1.0"
`;

// What a build under the private crate writes into the public lock: the stub has
// no dependencies at all, so a `dependencies = [` under that entry is the leak
// `check-no-private.sh` refuses to commit.
const POISONED_LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "sealwire-private"
version = "0.1.0"
dependencies = [
 "some-closed-source-dep",
]

[[package]]
name = "relay-api"
version = "0.1.0"
`;

function git(cwd, ...args) {
  const res = spawnSync("git", args, { cwd, encoding: "utf8" });
  assert.equal(res.status, 0, `git ${args.join(" ")} failed: ${res.stderr}`);
  return res.stdout;
}

/**
 * A miniature public checkout: the stub crate (with its marker), a clean lock,
 * and a copy of the real script. Committed, because the documented remedy for a
 * killed run is `git checkout -- crates/sealwire-private`.
 */
async function makeFixture() {
  const root = await mkdtemp(path.join(os.tmpdir(), "with-private-"));
  tempDirs.push(root);
  const repo = path.join(root, "repo");
  const priv = path.join(root, "sealwire-private");

  mkdirSync(path.join(repo, "crates/sealwire-private/src"), { recursive: true });
  mkdirSync(path.join(repo, "scripts"), { recursive: true });
  writeFileSync(path.join(repo, "crates/sealwire-private/STUB"), "stub marker\n");
  writeFileSync(
    path.join(repo, "crates/sealwire-private/Cargo.toml"),
    '[package]\nname = "sealwire-private"\nversion = "0.1.0"\n'
  );
  writeFileSync(path.join(repo, "crates/sealwire-private/src/lib.rs"), "// stub\n");
  writeFileSync(path.join(repo, "Cargo.lock"), CLEAN_LOCK);
  cpSync(realScript, path.join(repo, "scripts/with-private.sh"));

  git(repo, "init", "-q");
  git(repo, "add", "-A");
  git(repo, "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "-m", "init", "--no-verify");

  // The private checkout. PRIVATE_MARKER stands in for "closed sources are
  // here"; relay-api and optional relay-broker paths are rewritten on the way in.
  mkdirSync(path.join(priv, "src"), { recursive: true });
  writeFileSync(path.join(priv, "PRIVATE_MARKER"), "closed sources\n");
  writeFileSync(
    path.join(priv, "Cargo.toml"),
    '[package]\nname = "sealwire-private"\nversion = "0.1.0"\n\n' +
      "[dependencies]\n" +
      'relay-api = { path = "../agent-relay/crates/relay-api" }\n' +
      'relay-broker = { path = "../agent-relay/crates/relay-broker", optional = true }\n'
  );
  writeFileSync(path.join(priv, "src/lib.rs"), "// the real thing\n");

  return { root, repo, priv };
}

/** Leave the tree exactly as a SIGKILLed run does: private sources, no stub. */
function poison(repo, priv) {
  const target = path.join(repo, "crates/sealwire-private");
  rmSync(target, { recursive: true, force: true });
  cpSync(priv, target, { recursive: true });
  assert.ok(!existsSync(path.join(target, "STUB")), "fixture: poisoned tree still has STUB");
}

function run(repo, priv, command, env = {}) {
  return spawnSync("bash", [path.join(repo, "scripts/with-private.sh"), ...command], {
    cwd: repo,
    encoding: "utf8",
    env: { ...process.env, RELAY_PRIVATE_PATH: priv, ...env },
  });
}

const isStub = (repo) => existsSync(path.join(repo, "crates/sealwire-private/STUB"));
const hasPrivate = (repo) =>
  existsSync(path.join(repo, "crates/sealwire-private/PRIVATE_MARKER"));

// --- the swap itself still has to work -------------------------------------
// These two are the regression half: a guard that made the tree safe by never
// swapping anything in would pass the bug tests below and break every dev script.

test("the command runs with the private crate actually swapped in", async () => {
  const { repo, priv } = await makeFixture();

  const res = run(repo, priv, [
    "bash",
    "-c",
    'test -f crates/sealwire-private/PRIVATE_MARKER && echo swapped > witness',
  ]);

  assert.equal(res.status, 0, res.stderr);
  assert.equal(
    readFileSync(path.join(repo, "witness"), "utf8").trim(),
    "swapped",
    "the command did not see the private crate — the swap did not happen"
  );
  assert.ok(isStub(repo), "stub was not restored after a clean run");
  assert.ok(!hasPrivate(repo), "private sources left in the tree after a clean run");
});

test("the swap excludes the private checkout's node_modules", async () => {
  const { repo, priv } = await makeFixture();
  mkdirSync(path.join(priv, "node_modules/closed-dependency"), { recursive: true });
  writeFileSync(path.join(priv, "node_modules/closed-dependency/index.js"), "// dependency\n");

  const res = run(repo, priv, [
    "bash",
    "-c",
    "test ! -e crates/sealwire-private/node_modules",
  ]);

  assert.equal(res.status, 0, res.stderr);
  assert.ok(isStub(repo), "stub was not restored after the filtered swap");
});

test("swap rewrites relay-api and relay-broker paths then restores stub and lock", async () => {
  const { repo, priv } = await makeFixture();

  const res = run(repo, priv, [
    "bash",
    "-c",
    [
      "set -e",
      'grep -F \'path = "../relay-api"\' crates/sealwire-private/Cargo.toml',
      'grep -F \'path = "../relay-broker"\' crates/sealwire-private/Cargo.toml',
      '! grep -F \'../agent-relay/crates/relay-api\' crates/sealwire-private/Cargo.toml',
      '! grep -F \'../agent-relay/crates/relay-broker\' crates/sealwire-private/Cargo.toml',
    ].join(" && "),
  ]);

  assert.equal(res.status, 0, res.stderr || res.stdout);
  assert.ok(isStub(repo), "stub was not restored after path rewrite check");
  assert.ok(!hasPrivate(repo), "private sources left after path rewrite check");
  const lock = readFileSync(path.join(repo, "Cargo.lock"), "utf8");
  assert.equal(lock, CLEAN_LOCK, "Cargo.lock was not restored to the clean snapshot");
});

test("a failing command still restores, and its status propagates", async () => {
  const { repo, priv } = await makeFixture();

  const res = run(repo, priv, ["bash", "-c", "exit 3"]);

  assert.equal(res.status, 3, "exit status did not propagate");
  assert.ok(isStub(repo), "stub was not restored after a failing command");
  assert.ok(!hasPrivate(repo), "private sources left in the tree after a failing command");
});

// --- the bug ----------------------------------------------------------------

test("a tree left swapped by a killed run is not restored BACK to private sources", async () => {
  const { repo, priv } = await makeFixture();
  poison(repo, priv);

  const res = run(repo, priv, ["true"]);

  assert.notEqual(res.status, null, "script was killed rather than exiting");
  assert.ok(
    !hasPrivate(repo),
    "with-private.sh snapshotted the private sources as 'the stub' and restored them: " +
      "one killed run now poisons every later run, including the ones that exit cleanly"
  );
  assert.ok(isStub(repo), "the stub is not back in the tree");
});

test("a lock poisoned by a killed run is not snapshotted as the clean one", async () => {
  const { repo, priv } = await makeFixture();
  poison(repo, priv);
  writeFileSync(path.join(repo, "Cargo.lock"), POISONED_LOCK);

  run(repo, priv, ["true"]);

  const lock = readFileSync(path.join(repo, "Cargo.lock"), "utf8");
  assert.ok(
    !/^name = "sealwire-private"$\n^version.*$\n^dependencies = \[/m.test(lock),
    "the private crate's dependency list survived in the public Cargo.lock"
  );
});

test("the recovery is announced, not silent", async () => {
  const { repo, priv } = await makeFixture();
  poison(repo, priv);

  const res = run(repo, priv, ["true"]);

  assert.match(
    `${res.stdout}${res.stderr}`,
    /with-private/i,
    "the script healed (or failed to) without saying anything about it"
  );
});
